86c0b8vp3 sentry generator with ast
RonasIT/nx-generators pull request #50
Opened 2024-10-31 10:47 UTC by RuslanAktaev

2024-10-31 11:31 UTC, RuslanAktaev commented
@dmitryusenko review please!

FYI @ipakhomov

2024-11-01 08:32 UTC, dmitryusenko commented on plugin/src/generators/expo-app/schema.json
> +      "x-prompt": "Do you want to use sentry in your app?"
```suggestion
      "x-prompt": "Do you want to use Sentry in your app?"
```

2024-11-01 08:34 UTC, dmitryusenko commented on plugin/src/generators/next-app/schema.json
> +      "x-prompt": "Do you want to use sentry in your app?"
```suggestion
      "x-prompt": "Do you want to use Sentry in your app?"
```

2024-11-01 08:43 UTC, dmitryusenko commented on plugin/src/generators/sentry/files/sentry.client.config.ts.template
> +  dsn: '<%= DSN %>',
```suggestion
  dsn: '<%= dsn %>',
```

2024-11-01 08:43 UTC, dmitryusenko commented on plugin/src/generators/sentry/files/sentry.edge.config.ts.template
> +  dsn: '<%= DSN %>',
```suggestion
  dsn: '<%= dsn %>',
```

2024-11-01 08:43 UTC, dmitryusenko commented on plugin/src/generators/sentry/files/sentry.server.config.ts.template
> +  dsn: '<%= DSN %>',
```suggestion
  dsn: '<%= dsn %>',
```

2024-11-01 08:44 UTC, dmitryusenko commented on plugin/src/generators/sentry/schema.d.ts
> +  DSN: string;
```suggestion
  dsn: string;
```

2024-11-01 08:44 UTC, dmitryusenko commented on plugin/src/generators/sentry/schema.json
> +    "DSN": {
```suggestion
    "dsn": {
```

2024-11-01 08:49 UTC, dmitryusenko commented on plugin/src/generators/sentry/utils/generate-sentry-expo.ts
> +const updateExtraConfig = (content: string, DSN: string): string =>
```suggestion
const updateExtraConfig = (content: string, dsn: string): string =>
```

2024-11-01 08:57 UTC, dmitryusenko commented on plugin/src/generators/sentry/utils/generate-sentry-expo.ts
> +                  factory.createStringLiteral(DSN),
```suggestion
                  factory.createStringLiteral(dsn),
```

2024-11-01 08:57 UTC, dmitryusenko commented on plugin/src/generators/sentry/utils/generate-sentry-expo.ts
> +    options.DSN,
```suggestion
    options.dsn,
```

2024-11-01 09:42 UTC, dmitryusenko commented on plugin/src/generators/sentry/utils/generate-sentry-next.ts
> +  tree.write(`${projectRoot}/next.config.js`, updatedNextConfigContent);
We could implement some utility function to shorten the code that performs such file updates. Very rough idea:

```ts
function updateFile(tree, filePath, updater) {
  // 1. Call tree.read to get file contents
  // 2. Call updater over the file contents
  // 3. Call tree.write to write the updated file contents
}
```

2024-11-01 09:47 UTC, dmitryusenko commented
@RuslanAktaev Looks good to me overall! Please see a few suggestions above.

2024-11-01 09:49 UTC, dmitryusenko requested changes
@RuslanAktaev Looks good to me overall! I've provided the feedback above. Could you please address it?

2024-12-08 07:37 UTC, RuslanAktaev commented
@dmitryusenko fixed

2024-12-19 10:41 UTC, dmitryusenko commented
@RuslanAktaev Looks good to me, thanks!

@ipakhomov Could you please take a look?

2024-12-24 04:49 UTC, kerne1s commented on plugin/src/generators/sentry/generator.ts
> +  const projectRoot = `apps/${options.directory}`;
can't we use [selectProject](https://github.com/RonasIT/nx-generators/blob/main/plugin/src/shared/utils/cli-utils.ts#L98) from utils? So we can remove `x-prompt` for directory.

Example: https://github.com/RonasIT/nx-generators/blob/main/plugin/src/generators/react-lib/generator.ts#L22

2024-12-24 04:51 UTC, kerne1s commented on plugin/src/generators/sentry/utils/generate-sentry-expo.ts
> +};
please move it to our dependencies [file](https://github.com/RonasIT/nx-generators/blob/main/plugin/src/shared/dependencies.ts)

2024-12-24 04:53 UTC, kerne1s commented on plugin/src/generators/sentry/utils/generate-sentry-next.ts
> +};
as above

2024-12-24 05:01 UTC, kerne1s commented on plugin/src/shared/utils/is-next-app.ts
> +};
let's combine these utils:

```suggestion
export type AppFramework = 'expo' | 'next';

export const isNextApp = (tree: Tree, projectRoot: string): boolean => {
  return tree.exists(`${projectRoot}/next.config.js`);
};

export const isExpoApp = (tree: Tree, projectRoot: string): boolean => {
  return tree.exists(`${projectRoot}/metro.config.js`);
};

export const getAppFrameworkName = (tree: Tree, projectRoot: string): AppFramework => {
  return isNextApp(tree, projectRoot) ? 'next' : isExpoApp(tree, projectRoot) ? 'expo' :  undefined;
};
```

2024-12-24 05:04 UTC, kerne1s commented on plugin/src/shared/utils/update-file.ts
> +export const updateFile = (
we have a similar [utility](https://github.com/RonasIT/nx-generators/blob/main/plugin/src/shared/utils/cli-utils.ts#L87), can we modify it to use updateFile?

2025-02-07 10:32 UTC, RuslanAktaev commented
@kerne1s thanks, fixed!

2025-02-07 11:37 UTC, kerne1s commented on plugin/src/shared/utils/cli-utils.ts
> +// TODO: Test this one
@RuslanAktaev please resolve

2025-02-07 11:40 UTC, RuslanAktaev commented on plugin/src/shared/utils/cli-utils.ts
> +// TODO: Test this one
@kerne1s done

2025-02-07 12:39 UTC, merged